name: CI

on:
  push:
    branches: [ feature/ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.X
    - run: npm ci
    - run: npm run build
    - name: npm publish
      run: |
        npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
        npm publish
