name: Quality assurance

on:
  push:
    branches-ignore: [master]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Unpack dependencies cache
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install npm dependencies
      run: npm ci --prefer-offline

    - name: Lint with ESLint
      run: npx eslint .

  build:
    name: Ensure library builds
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Unpack dependencies cache
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install npm dependencies
      run: npm ci --prefer-offline

    - name: Build library
      run: npm run build

    - name: Build example spec
      run: npx ts-node example/bin/build.ts
